//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtuosoEventService.VirtuosoCentral {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:8890/EventFrameworkProcedures/services.wsdl", ConfigurationName="VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType")]
    public interface EventFrameworkProceduresDocLiteralPortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (services.wsdl) of message RDF_EVENT_FRAMEWORK_GET_SCHEMA_TABLESRequest does not match the default value (http://localhost:8890/EventFrameworkProcedures/services.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="http://openlinksw.com/virtuoso/soap/schema#RDF_EVENT_FRAMEWORK_GET_SCHEMA_TABLES", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_GET_SCHEMA_TABLESResponse RDF_EVENT_FRAMEWORK_GET_SCHEMA_TABLES(VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_GET_SCHEMA_TABLESRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (services.wsdl) of message RDF_EVENT_FRAMEWORK_SET_NEW_TRIGGERRequest does not match the default value (http://localhost:8890/EventFrameworkProcedures/services.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="http://openlinksw.com/virtuoso/soap/schema#RDF_EVENT_FRAMEWORK_SET_NEW_TRIGGER", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_SET_NEW_TRIGGERResponse RDF_EVENT_FRAMEWORK_SET_NEW_TRIGGER(VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_SET_NEW_TRIGGERRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (services.wsdl) of message ERR_MAIL_SENDRequest does not match the default value (http://localhost:8890/EventFrameworkProcedures/services.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="http://openlinksw.com/virtuoso/soap/schema#ERR_MAIL_SEND", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        VirtuosoEventService.VirtuosoCentral.ERR_MAIL_SENDResponse ERR_MAIL_SEND(VirtuosoEventService.VirtuosoCentral.ERR_MAIL_SENDRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (services.wsdl) of message VFS_ROBOTS_GETRequest does not match the default value (http://localhost:8890/EventFrameworkProcedures/services.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="http://openlinksw.com/virtuoso/soap/schema#VFS_ROBOTS_GET", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        VirtuosoEventService.VirtuosoCentral.VFS_ROBOTS_GETResponse VFS_ROBOTS_GET(VirtuosoEventService.VirtuosoCentral.VFS_ROBOTS_GETRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (services.wsdl) of message RDF_EVENT_FRAMEWORK_INSERT_CONSTANTRequest does not match the default value (http://localhost:8890/EventFrameworkProcedures/services.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="http://openlinksw.com/virtuoso/soap/schema#RDF_EVENT_FRAMEWORK_INSERT_CONSTANT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_INSERT_CONSTANTResponse RDF_EVENT_FRAMEWORK_INSERT_CONSTANT(VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_INSERT_CONSTANTRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (services.wsdl) of message RDF_EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLERequest does not match the default value (http://localhost:8890/EventFrameworkProcedures/services.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="http://openlinksw.com/virtuoso/soap/schema#RDF_EVENT_FRAMEWORK_GET_TRIGGERS_OF_TA" +
            "BLE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLEResponse RDF_EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLE(VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLERequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (services.wsdl) of message RDF_EVENT_FRAMEWORK_GET_TRIGGER_SYNTAXRequest does not match the default value (http://localhost:8890/EventFrameworkProcedures/services.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="http://openlinksw.com/virtuoso/soap/schema#RDF_EVENT_FRAMEWORK_GET_TRIGGER_SYNTAX" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_GET_TRIGGER_SYNTAXResponse RDF_EVENT_FRAMEWORK_GET_TRIGGER_SYNTAX(VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_GET_TRIGGER_SYNTAXRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (services.wsdl) of message VFS_ROBOTS_PARSERequest does not match the default value (http://localhost:8890/EventFrameworkProcedures/services.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="http://openlinksw.com/virtuoso/soap/schema#VFS_ROBOTS_PARSE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        VirtuosoEventService.VirtuosoCentral.VFS_ROBOTS_PARSEResponse VFS_ROBOTS_PARSE(VirtuosoEventService.VirtuosoCentral.VFS_ROBOTS_PARSERequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (services.wsdl) of message RDF_EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTSRequest does not match the default value (http://localhost:8890/EventFrameworkProcedures/services.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="http://openlinksw.com/virtuoso/soap/schema#RDF_EVENT_FRAMEWORK_CHECK_TRIGGER_EXIS" +
            "TS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTSResponse RDF_EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTS(VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTSRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (services.wsdl) of message RDF_EVENT_FRAMEWORK_REGISTER_REMOTE_DBRequest does not match the default value (http://localhost:8890/EventFrameworkProcedures/services.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="http://openlinksw.com/virtuoso/soap/schema#RDF_EVENT_FRAMEWORK_REGISTER_REMOTE_DB" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_REGISTER_REMOTE_DBResponse RDF_EVENT_FRAMEWORK_REGISTER_REMOTE_DB(VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_REGISTER_REMOTE_DBRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (services.wsdl) of message RDF_EVENT_FRAMEWORK_INSERT_NEW_EVENTRequest does not match the default value (http://localhost:8890/EventFrameworkProcedures/services.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="http://openlinksw.com/virtuoso/soap/schema#RDF_EVENT_FRAMEWORK_INSERT_NEW_EVENT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_INSERT_NEW_EVENTResponse RDF_EVENT_FRAMEWORK_INSERT_NEW_EVENT(VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_INSERT_NEW_EVENTRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (services.wsdl) of message EVENT_FRAMEWORK_TEST_SQL_CONDITIONRequest does not match the default value (http://localhost:8890/EventFrameworkProcedures/services.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="http://openlinksw.com/virtuoso/soap/schema#EVENT_FRAMEWORK_TEST_SQL_CONDITION", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_TEST_SQL_CONDITIONResponse EVENT_FRAMEWORK_TEST_SQL_CONDITION(VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_TEST_SQL_CONDITIONRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RDF_EVENT_FRAMEWORK_GET_SCHEMA_TABLES", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class RDF_EVENT_FRAMEWORK_GET_SCHEMA_TABLESRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DBschema;
        
        public RDF_EVENT_FRAMEWORK_GET_SCHEMA_TABLESRequest() {
        }
        
        public RDF_EVENT_FRAMEWORK_GET_SCHEMA_TABLESRequest(string DBschema) {
            this.DBschema = DBschema;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RDF_EVENT_FRAMEWORK_GET_SCHEMA_TABLESResponse", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class RDF_EVENT_FRAMEWORK_GET_SCHEMA_TABLESResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] CallReturn;
        
        public RDF_EVENT_FRAMEWORK_GET_SCHEMA_TABLESResponse() {
        }
        
        public RDF_EVENT_FRAMEWORK_GET_SCHEMA_TABLESResponse(string[] CallReturn) {
            this.CallReturn = CallReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RDF_EVENT_FRAMEWORK_SET_NEW_TRIGGER", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class RDF_EVENT_FRAMEWORK_SET_NEW_TRIGGERRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string statement;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tablee;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string database;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string triggerName;
        
        public RDF_EVENT_FRAMEWORK_SET_NEW_TRIGGERRequest() {
        }
        
        public RDF_EVENT_FRAMEWORK_SET_NEW_TRIGGERRequest(string statement, string tablee, string database, string triggerName) {
            this.statement = statement;
            this.tablee = tablee;
            this.database = database;
            this.triggerName = triggerName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RDF_EVENT_FRAMEWORK_SET_NEW_TRIGGERResponse", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class RDF_EVENT_FRAMEWORK_SET_NEW_TRIGGERResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CallReturn;
        
        public RDF_EVENT_FRAMEWORK_SET_NEW_TRIGGERResponse() {
        }
        
        public RDF_EVENT_FRAMEWORK_SET_NEW_TRIGGERResponse(string CallReturn) {
            this.CallReturn = CallReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ERR_MAIL_SEND", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class ERR_MAIL_SENDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _tgt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _urls;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _root;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _stat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _msg;
        
        public ERR_MAIL_SENDRequest() {
        }
        
        public ERR_MAIL_SENDRequest(string _tgt, string _urls, string _root, string _stat, string _msg) {
            this._tgt = _tgt;
            this._urls = _urls;
            this._root = _root;
            this._stat = _stat;
            this._msg = _msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ERR_MAIL_SENDResponse", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class ERR_MAIL_SENDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CallReturn;
        
        public ERR_MAIL_SENDResponse() {
        }
        
        public ERR_MAIL_SENDResponse(string CallReturn) {
            this.CallReturn = CallReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VFS_ROBOTS_GET", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class VFS_ROBOTS_GETRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _host;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _root;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string site_delay_sec;
        
        public VFS_ROBOTS_GETRequest() {
        }
        
        public VFS_ROBOTS_GETRequest(string _host, string _root, string site_delay_sec) {
            this._host = _host;
            this._root = _root;
            this.site_delay_sec = site_delay_sec;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VFS_ROBOTS_GETResponse", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class VFS_ROBOTS_GETResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string site_delay_sec;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CallReturn;
        
        public VFS_ROBOTS_GETResponse() {
        }
        
        public VFS_ROBOTS_GETResponse(string site_delay_sec, string CallReturn) {
            this.site_delay_sec = site_delay_sec;
            this.CallReturn = CallReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RDF_EVENT_FRAMEWORK_INSERT_CONSTANT", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class RDF_EVENT_FRAMEWORK_INSERT_CONSTANTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string keyV;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string valueV;
        
        public RDF_EVENT_FRAMEWORK_INSERT_CONSTANTRequest() {
        }
        
        public RDF_EVENT_FRAMEWORK_INSERT_CONSTANTRequest(string keyV, string valueV) {
            this.keyV = keyV;
            this.valueV = valueV;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RDF_EVENT_FRAMEWORK_INSERT_CONSTANTResponse", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class RDF_EVENT_FRAMEWORK_INSERT_CONSTANTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CallReturn;
        
        public RDF_EVENT_FRAMEWORK_INSERT_CONSTANTResponse() {
        }
        
        public RDF_EVENT_FRAMEWORK_INSERT_CONSTANTResponse(string CallReturn) {
            this.CallReturn = CallReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RDF_EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLE", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class RDF_EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tablename;
        
        public RDF_EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLERequest() {
        }
        
        public RDF_EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLERequest(string tablename) {
            this.tablename = tablename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RDF_EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLEResponse", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class RDF_EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] CallReturn;
        
        public RDF_EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLEResponse() {
        }
        
        public RDF_EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLEResponse(string[] CallReturn) {
            this.CallReturn = CallReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RDF_EVENT_FRAMEWORK_GET_TRIGGER_SYNTAX", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class RDF_EVENT_FRAMEWORK_GET_TRIGGER_SYNTAXRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tablename;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string triggername;
        
        public RDF_EVENT_FRAMEWORK_GET_TRIGGER_SYNTAXRequest() {
        }
        
        public RDF_EVENT_FRAMEWORK_GET_TRIGGER_SYNTAXRequest(string tablename, string triggername) {
            this.tablename = tablename;
            this.triggername = triggername;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RDF_EVENT_FRAMEWORK_GET_TRIGGER_SYNTAXResponse", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class RDF_EVENT_FRAMEWORK_GET_TRIGGER_SYNTAXResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CallReturn;
        
        public RDF_EVENT_FRAMEWORK_GET_TRIGGER_SYNTAXResponse() {
        }
        
        public RDF_EVENT_FRAMEWORK_GET_TRIGGER_SYNTAXResponse(string CallReturn) {
            this.CallReturn = CallReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VFS_ROBOTS_PARSE", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class VFS_ROBOTS_PARSERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string txt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ua;
        
        public VFS_ROBOTS_PARSERequest() {
        }
        
        public VFS_ROBOTS_PARSERequest(string txt, string ua) {
            this.txt = txt;
            this.ua = ua;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VFS_ROBOTS_PARSEResponse", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class VFS_ROBOTS_PARSEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double delay_sec;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CallReturn;
        
        public VFS_ROBOTS_PARSEResponse() {
        }
        
        public VFS_ROBOTS_PARSEResponse(double delay_sec, string CallReturn) {
            this.delay_sec = delay_sec;
            this.CallReturn = CallReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RDF_EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTS", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class RDF_EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tablename;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string triggername;
        
        public RDF_EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTSRequest() {
        }
        
        public RDF_EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTSRequest(string tablename, string triggername) {
            this.tablename = tablename;
            this.triggername = triggername;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RDF_EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTSResponse", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class RDF_EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CallReturn;
        
        public RDF_EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTSResponse() {
        }
        
        public RDF_EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTSResponse(string CallReturn) {
            this.CallReturn = CallReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RDF_EVENT_FRAMEWORK_REGISTER_REMOTE_DB", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class RDF_EVENT_FRAMEWORK_REGISTER_REMOTE_DBRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string catalogSchema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dbType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string description;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string remoteSoapEndpoint;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string remoteSparqlEndpoint;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rdfGraphCommaList;
        
        public RDF_EVENT_FRAMEWORK_REGISTER_REMOTE_DBRequest() {
        }
        
        public RDF_EVENT_FRAMEWORK_REGISTER_REMOTE_DBRequest(string catalogSchema, string dbType, string description, string remoteSoapEndpoint, string remoteSparqlEndpoint, string rdfGraphCommaList) {
            this.catalogSchema = catalogSchema;
            this.dbType = dbType;
            this.description = description;
            this.remoteSoapEndpoint = remoteSoapEndpoint;
            this.remoteSparqlEndpoint = remoteSparqlEndpoint;
            this.rdfGraphCommaList = rdfGraphCommaList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RDF_EVENT_FRAMEWORK_REGISTER_REMOTE_DBResponse", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class RDF_EVENT_FRAMEWORK_REGISTER_REMOTE_DBResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CallReturn;
        
        public RDF_EVENT_FRAMEWORK_REGISTER_REMOTE_DBResponse() {
        }
        
        public RDF_EVENT_FRAMEWORK_REGISTER_REMOTE_DBResponse(string CallReturn) {
            this.CallReturn = CallReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RDF_EVENT_FRAMEWORK_INSERT_NEW_EVENT", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class RDF_EVENT_FRAMEWORK_INSERT_NEW_EVENTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int instance;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tableName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string triggerName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime occurence;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rowVector;
        
        public RDF_EVENT_FRAMEWORK_INSERT_NEW_EVENTRequest() {
        }
        
        public RDF_EVENT_FRAMEWORK_INSERT_NEW_EVENTRequest(int instance, string tableName, string triggerName, System.DateTime occurence, string rowVector) {
            this.instance = instance;
            this.tableName = tableName;
            this.triggerName = triggerName;
            this.occurence = occurence;
            this.rowVector = rowVector;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RDF_EVENT_FRAMEWORK_INSERT_NEW_EVENTResponse", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class RDF_EVENT_FRAMEWORK_INSERT_NEW_EVENTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CallReturn;
        
        public RDF_EVENT_FRAMEWORK_INSERT_NEW_EVENTResponse() {
        }
        
        public RDF_EVENT_FRAMEWORK_INSERT_NEW_EVENTResponse(string CallReturn) {
            this.CallReturn = CallReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EVENT_FRAMEWORK_TEST_SQL_CONDITION", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class EVENT_FRAMEWORK_TEST_SQL_CONDITIONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string executeQuerry;
        
        public EVENT_FRAMEWORK_TEST_SQL_CONDITIONRequest() {
        }
        
        public EVENT_FRAMEWORK_TEST_SQL_CONDITIONRequest(string executeQuerry) {
            this.executeQuerry = executeQuerry;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EVENT_FRAMEWORK_TEST_SQL_CONDITIONResponse", WrapperNamespace="services.wsdl", IsWrapped=true)]
    public partial class EVENT_FRAMEWORK_TEST_SQL_CONDITIONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.wsdl", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, NestingLevel=1)]
        public string[][] CallReturn;
        
        public EVENT_FRAMEWORK_TEST_SQL_CONDITIONResponse() {
        }
        
        public EVENT_FRAMEWORK_TEST_SQL_CONDITIONResponse(string[][] CallReturn) {
            this.CallReturn = CallReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EventFrameworkProceduresDocLiteralPortTypeChannel : VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EventFrameworkProceduresDocLiteralPortTypeClient : System.ServiceModel.ClientBase<VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType>, VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType {
        
        public EventFrameworkProceduresDocLiteralPortTypeClient() {
        }
        
        public EventFrameworkProceduresDocLiteralPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EventFrameworkProceduresDocLiteralPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventFrameworkProceduresDocLiteralPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventFrameworkProceduresDocLiteralPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_GET_SCHEMA_TABLESResponse VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType.RDF_EVENT_FRAMEWORK_GET_SCHEMA_TABLES(VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_GET_SCHEMA_TABLESRequest request) {
            return base.Channel.RDF_EVENT_FRAMEWORK_GET_SCHEMA_TABLES(request);
        }
        
        public string[] RDF_EVENT_FRAMEWORK_GET_SCHEMA_TABLES(string DBschema) {
            VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_GET_SCHEMA_TABLESRequest inValue = new VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_GET_SCHEMA_TABLESRequest();
            inValue.DBschema = DBschema;
            VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_GET_SCHEMA_TABLESResponse retVal = ((VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType)(this)).RDF_EVENT_FRAMEWORK_GET_SCHEMA_TABLES(inValue);
            return retVal.CallReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_SET_NEW_TRIGGERResponse VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType.RDF_EVENT_FRAMEWORK_SET_NEW_TRIGGER(VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_SET_NEW_TRIGGERRequest request) {
            return base.Channel.RDF_EVENT_FRAMEWORK_SET_NEW_TRIGGER(request);
        }
        
        public string RDF_EVENT_FRAMEWORK_SET_NEW_TRIGGER(string statement, string tablee, string database, string triggerName) {
            VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_SET_NEW_TRIGGERRequest inValue = new VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_SET_NEW_TRIGGERRequest();
            inValue.statement = statement;
            inValue.tablee = tablee;
            inValue.database = database;
            inValue.triggerName = triggerName;
            VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_SET_NEW_TRIGGERResponse retVal = ((VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType)(this)).RDF_EVENT_FRAMEWORK_SET_NEW_TRIGGER(inValue);
            return retVal.CallReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VirtuosoEventService.VirtuosoCentral.ERR_MAIL_SENDResponse VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType.ERR_MAIL_SEND(VirtuosoEventService.VirtuosoCentral.ERR_MAIL_SENDRequest request) {
            return base.Channel.ERR_MAIL_SEND(request);
        }
        
        public string ERR_MAIL_SEND(string _tgt, string _urls, string _root, string _stat, string _msg) {
            VirtuosoEventService.VirtuosoCentral.ERR_MAIL_SENDRequest inValue = new VirtuosoEventService.VirtuosoCentral.ERR_MAIL_SENDRequest();
            inValue._tgt = _tgt;
            inValue._urls = _urls;
            inValue._root = _root;
            inValue._stat = _stat;
            inValue._msg = _msg;
            VirtuosoEventService.VirtuosoCentral.ERR_MAIL_SENDResponse retVal = ((VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType)(this)).ERR_MAIL_SEND(inValue);
            return retVal.CallReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VirtuosoEventService.VirtuosoCentral.VFS_ROBOTS_GETResponse VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType.VFS_ROBOTS_GET(VirtuosoEventService.VirtuosoCentral.VFS_ROBOTS_GETRequest request) {
            return base.Channel.VFS_ROBOTS_GET(request);
        }
        
        public string VFS_ROBOTS_GET(string _host, string _root, ref string site_delay_sec) {
            VirtuosoEventService.VirtuosoCentral.VFS_ROBOTS_GETRequest inValue = new VirtuosoEventService.VirtuosoCentral.VFS_ROBOTS_GETRequest();
            inValue._host = _host;
            inValue._root = _root;
            inValue.site_delay_sec = site_delay_sec;
            VirtuosoEventService.VirtuosoCentral.VFS_ROBOTS_GETResponse retVal = ((VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType)(this)).VFS_ROBOTS_GET(inValue);
            site_delay_sec = retVal.site_delay_sec;
            return retVal.CallReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_INSERT_CONSTANTResponse VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType.RDF_EVENT_FRAMEWORK_INSERT_CONSTANT(VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_INSERT_CONSTANTRequest request) {
            return base.Channel.RDF_EVENT_FRAMEWORK_INSERT_CONSTANT(request);
        }
        
        public string RDF_EVENT_FRAMEWORK_INSERT_CONSTANT(string keyV, string valueV) {
            VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_INSERT_CONSTANTRequest inValue = new VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_INSERT_CONSTANTRequest();
            inValue.keyV = keyV;
            inValue.valueV = valueV;
            VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_INSERT_CONSTANTResponse retVal = ((VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType)(this)).RDF_EVENT_FRAMEWORK_INSERT_CONSTANT(inValue);
            return retVal.CallReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLEResponse VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType.RDF_EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLE(VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLERequest request) {
            return base.Channel.RDF_EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLE(request);
        }
        
        public string[] RDF_EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLE(string tablename) {
            VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLERequest inValue = new VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLERequest();
            inValue.tablename = tablename;
            VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLEResponse retVal = ((VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType)(this)).RDF_EVENT_FRAMEWORK_GET_TRIGGERS_OF_TABLE(inValue);
            return retVal.CallReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_GET_TRIGGER_SYNTAXResponse VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType.RDF_EVENT_FRAMEWORK_GET_TRIGGER_SYNTAX(VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_GET_TRIGGER_SYNTAXRequest request) {
            return base.Channel.RDF_EVENT_FRAMEWORK_GET_TRIGGER_SYNTAX(request);
        }
        
        public string RDF_EVENT_FRAMEWORK_GET_TRIGGER_SYNTAX(string tablename, string triggername) {
            VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_GET_TRIGGER_SYNTAXRequest inValue = new VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_GET_TRIGGER_SYNTAXRequest();
            inValue.tablename = tablename;
            inValue.triggername = triggername;
            VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_GET_TRIGGER_SYNTAXResponse retVal = ((VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType)(this)).RDF_EVENT_FRAMEWORK_GET_TRIGGER_SYNTAX(inValue);
            return retVal.CallReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VirtuosoEventService.VirtuosoCentral.VFS_ROBOTS_PARSEResponse VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType.VFS_ROBOTS_PARSE(VirtuosoEventService.VirtuosoCentral.VFS_ROBOTS_PARSERequest request) {
            return base.Channel.VFS_ROBOTS_PARSE(request);
        }
        
        public double VFS_ROBOTS_PARSE(string txt, string ua, out string CallReturn) {
            VirtuosoEventService.VirtuosoCentral.VFS_ROBOTS_PARSERequest inValue = new VirtuosoEventService.VirtuosoCentral.VFS_ROBOTS_PARSERequest();
            inValue.txt = txt;
            inValue.ua = ua;
            VirtuosoEventService.VirtuosoCentral.VFS_ROBOTS_PARSEResponse retVal = ((VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType)(this)).VFS_ROBOTS_PARSE(inValue);
            CallReturn = retVal.CallReturn;
            return retVal.delay_sec;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTSResponse VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType.RDF_EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTS(VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTSRequest request) {
            return base.Channel.RDF_EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTS(request);
        }
        
        public string RDF_EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTS(string tablename, string triggername) {
            VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTSRequest inValue = new VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTSRequest();
            inValue.tablename = tablename;
            inValue.triggername = triggername;
            VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTSResponse retVal = ((VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType)(this)).RDF_EVENT_FRAMEWORK_CHECK_TRIGGER_EXISTS(inValue);
            return retVal.CallReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_REGISTER_REMOTE_DBResponse VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType.RDF_EVENT_FRAMEWORK_REGISTER_REMOTE_DB(VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_REGISTER_REMOTE_DBRequest request) {
            return base.Channel.RDF_EVENT_FRAMEWORK_REGISTER_REMOTE_DB(request);
        }
        
        public string RDF_EVENT_FRAMEWORK_REGISTER_REMOTE_DB(string catalogSchema, string dbType, string description, string remoteSoapEndpoint, string remoteSparqlEndpoint, string rdfGraphCommaList) {
            VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_REGISTER_REMOTE_DBRequest inValue = new VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_REGISTER_REMOTE_DBRequest();
            inValue.catalogSchema = catalogSchema;
            inValue.dbType = dbType;
            inValue.description = description;
            inValue.remoteSoapEndpoint = remoteSoapEndpoint;
            inValue.remoteSparqlEndpoint = remoteSparqlEndpoint;
            inValue.rdfGraphCommaList = rdfGraphCommaList;
            VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_REGISTER_REMOTE_DBResponse retVal = ((VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType)(this)).RDF_EVENT_FRAMEWORK_REGISTER_REMOTE_DB(inValue);
            return retVal.CallReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_INSERT_NEW_EVENTResponse VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType.RDF_EVENT_FRAMEWORK_INSERT_NEW_EVENT(VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_INSERT_NEW_EVENTRequest request) {
            return base.Channel.RDF_EVENT_FRAMEWORK_INSERT_NEW_EVENT(request);
        }
        
        public string RDF_EVENT_FRAMEWORK_INSERT_NEW_EVENT(int instance, string tableName, string triggerName, System.DateTime occurence, string rowVector) {
            VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_INSERT_NEW_EVENTRequest inValue = new VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_INSERT_NEW_EVENTRequest();
            inValue.instance = instance;
            inValue.tableName = tableName;
            inValue.triggerName = triggerName;
            inValue.occurence = occurence;
            inValue.rowVector = rowVector;
            VirtuosoEventService.VirtuosoCentral.RDF_EVENT_FRAMEWORK_INSERT_NEW_EVENTResponse retVal = ((VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType)(this)).RDF_EVENT_FRAMEWORK_INSERT_NEW_EVENT(inValue);
            return retVal.CallReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_TEST_SQL_CONDITIONResponse VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType.EVENT_FRAMEWORK_TEST_SQL_CONDITION(VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_TEST_SQL_CONDITIONRequest request) {
            return base.Channel.EVENT_FRAMEWORK_TEST_SQL_CONDITION(request);
        }
        
        public string[][] EVENT_FRAMEWORK_TEST_SQL_CONDITION(string executeQuerry) {
            VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_TEST_SQL_CONDITIONRequest inValue = new VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_TEST_SQL_CONDITIONRequest();
            inValue.executeQuerry = executeQuerry;
            VirtuosoEventService.VirtuosoCentral.EVENT_FRAMEWORK_TEST_SQL_CONDITIONResponse retVal = ((VirtuosoEventService.VirtuosoCentral.EventFrameworkProceduresDocLiteralPortType)(this)).EVENT_FRAMEWORK_TEST_SQL_CONDITION(inValue);
            return retVal.CallReturn;
        }
    }
}
