//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RdfEventClientConcoleTest.VirtuosoEventServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VirtuosoEventServiceRef.IVirtuosoEventService")]
    public interface IVirtuosoEventService {
        
        // CODEGEN: Parameter 'GetTriplesResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVirtuosoEventService/GetTriples", ReplyAction="http://tempuri.org/IVirtuosoEventService/GetTriplesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        RdfEventClientConcoleTest.VirtuosoEventServiceRef.GetTriplesResponse GetTriples(RdfEventClientConcoleTest.VirtuosoEventServiceRef.GetTriplesRequest request);
        
        // CODEGEN: Parameter 'GetTripleResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVirtuosoEventService/GetTriple", ReplyAction="http://tempuri.org/IVirtuosoEventService/GetTripleResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        RdfEventClientConcoleTest.VirtuosoEventServiceRef.GetTripleResponse GetTriple(RdfEventClientConcoleTest.VirtuosoEventServiceRef.GetTripleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVirtuosoEventService/InsertTriple", ReplyAction="http://tempuri.org/IVirtuosoEventService/InsertTripleResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void InsertTriple(string graph, string subj, string pred, string obj);
        
        // CODEGEN: Parameter 'LogInResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVirtuosoEventService/LogIn", ReplyAction="http://tempuri.org/IVirtuosoEventService/LogInResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        RdfEventClientConcoleTest.VirtuosoEventServiceRef.LogInResponse LogIn(RdfEventClientConcoleTest.VirtuosoEventServiceRef.LogInRequest request);
        
        // CODEGEN: Parameter 'userName' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVirtuosoEventService/CreateNewAccount", ReplyAction="http://tempuri.org/IVirtuosoEventService/CreateNewAccountResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        RdfEventClientConcoleTest.VirtuosoEventServiceRef.CreateNewAccountResponse CreateNewAccount(RdfEventClientConcoleTest.VirtuosoEventServiceRef.CreateNewAccountRequest request);
        
        // CODEGEN: Parameter 'GetUsersResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVirtuosoEventService/GetUsers", ReplyAction="http://tempuri.org/IVirtuosoEventService/GetUsersResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        RdfEventClientConcoleTest.VirtuosoEventServiceRef.GetUsersResponse GetUsers(RdfEventClientConcoleTest.VirtuosoEventServiceRef.GetUsersRequest request);
        
        // CODEGEN: Parameter 'CollectEventsResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVirtuosoEventService/CollectEvents", ReplyAction="http://tempuri.org/IVirtuosoEventService/CollectEventsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        RdfEventClientConcoleTest.VirtuosoEventServiceRef.CollectEventsResponse CollectEvents(RdfEventClientConcoleTest.VirtuosoEventServiceRef.CollectEventsRequest request);
        
        // CODEGEN: Parameter 'newPass' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVirtuosoEventService/ResetUserpassword", ReplyAction="http://tempuri.org/IVirtuosoEventService/ResetUserpasswordResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        RdfEventClientConcoleTest.VirtuosoEventServiceRef.ResetUserpasswordResponse ResetUserpassword(RdfEventClientConcoleTest.VirtuosoEventServiceRef.ResetUserpasswordRequest request);
        
        // CODEGEN: Parameter 'userName' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVirtuosoEventService/SetUserAccRights", ReplyAction="http://tempuri.org/IVirtuosoEventService/SetUserAccRightsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        RdfEventClientConcoleTest.VirtuosoEventServiceRef.SetUserAccRightsResponse SetUserAccRights(RdfEventClientConcoleTest.VirtuosoEventServiceRef.SetUserAccRightsRequest request);
        
        // CODEGEN: Parameter 'userName' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVirtuosoEventService/SetEventDefRights", ReplyAction="http://tempuri.org/IVirtuosoEventService/SetEventDefRightsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        RdfEventClientConcoleTest.VirtuosoEventServiceRef.SetEventDefRightsResponse SetEventDefRights(RdfEventClientConcoleTest.VirtuosoEventServiceRef.SetEventDefRightsRequest request);
        
        // CODEGEN: Parameter 'connectionString' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVirtuosoEventService/RegisterVirtuosoDB", ReplyAction="http://tempuri.org/IVirtuosoEventService/RegisterVirtuosoDBResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        RdfEventClientConcoleTest.VirtuosoEventServiceRef.RegisterVirtuosoDBResponse RegisterVirtuosoDB(RdfEventClientConcoleTest.VirtuosoEventServiceRef.RegisterVirtuosoDBRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVirtuosoEventService/CreateTrigger", ReplyAction="http://tempuri.org/IVirtuosoEventService/CreateTriggerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        bool CreateTrigger();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/VirtuosoEventService")]
    public partial class TripleType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string objectField;
        
        private string predicateField;
        
        private string subjectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Object {
            get {
                return this.objectField;
            }
            set {
                this.objectField = value;
                this.RaisePropertyChanged("Object");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Predicate {
            get {
                return this.predicateField;
            }
            set {
                this.predicateField = value;
                this.RaisePropertyChanged("Predicate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
                this.RaisePropertyChanged("Subject");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTriples", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTriplesRequest {
        
        public GetTriplesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTriplesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTriplesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/VirtuosoEventService")]
        public TripleType[] GetTriplesResult;
        
        public GetTriplesResponse() {
        }
        
        public GetTriplesResponse(TripleType[] GetTriplesResult) {
            this.GetTriplesResult = GetTriplesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTriple", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTripleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int index;
        
        public GetTripleRequest() {
        }
        
        public GetTripleRequest(int index) {
            this.index = index;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTripleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTripleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RdfEventClientConcoleTest.VirtuosoEventServiceRef.TripleType GetTripleResult;
        
        public GetTripleResponse() {
        }
        
        public GetTripleResponse(RdfEventClientConcoleTest.VirtuosoEventServiceRef.TripleType GetTripleResult) {
            this.GetTripleResult = GetTripleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogIn", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LogInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        public LogInRequest() {
        }
        
        public LogInRequest(string userName, string password) {
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogInResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LogInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LogInResult;
        
        public LogInResponse() {
        }
        
        public LogInResponse(string LogInResult) {
            this.LogInResult = LogInResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateNewAccount", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateNewAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        public CreateNewAccountRequest() {
        }
        
        public CreateNewAccountRequest(string userName, string password) {
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateNewAccountResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateNewAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool CreateNewAccountResult;
        
        public CreateNewAccountResponse() {
        }
        
        public CreateNewAccountResponse(bool CreateNewAccountResult) {
            this.CreateNewAccountResult = CreateNewAccountResult;
        }
    }
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    // This type definition was generated by System.Data.Design.TypedDataSetSchemaImporterExtensionFx35 schema importer extension.
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("VirtuosoDataSet")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class VirtuosoDataSet : global::System.Data.DataSet {
        
        private VirtuosoDataTableDataTable tableVirtuosoDataTable;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public VirtuosoDataSet() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected VirtuosoDataSet(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["VirtuosoDataTable"] != null)) {
                    base.Tables.Add(new VirtuosoDataTableDataTable(ds.Tables["VirtuosoDataTable"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public VirtuosoDataTableDataTable VirtuosoDataTable {
            get {
                return this.tableVirtuosoDataTable;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            VirtuosoDataSet cln = ((VirtuosoDataSet)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["VirtuosoDataTable"] != null)) {
                    base.Tables.Add(new VirtuosoDataTableDataTable(ds.Tables["VirtuosoDataTable"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableVirtuosoDataTable = ((VirtuosoDataTableDataTable)(base.Tables["VirtuosoDataTable"]));
            if ((initTable == true)) {
                if ((this.tableVirtuosoDataTable != null)) {
                    this.tableVirtuosoDataTable.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "VirtuosoDataSet";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/VirtuosoDataSet.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableVirtuosoDataTable = new VirtuosoDataTableDataTable();
            base.Tables.Add(this.tableVirtuosoDataTable);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializeVirtuosoDataTable() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            VirtuosoDataSet ds = new VirtuosoDataSet();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void VirtuosoDataTableRowChangeEventHandler(object sender, VirtuosoDataTableRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class VirtuosoDataTableDataTable : global::System.Data.TypedTableBase<VirtuosoDataTableRow> {
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public VirtuosoDataTableDataTable() {
                this.TableName = "VirtuosoDataTable";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal VirtuosoDataTableDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected VirtuosoDataTableDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public VirtuosoDataTableRow this[int index] {
                get {
                    return ((VirtuosoDataTableRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event VirtuosoDataTableRowChangeEventHandler VirtuosoDataTableRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event VirtuosoDataTableRowChangeEventHandler VirtuosoDataTableRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event VirtuosoDataTableRowChangeEventHandler VirtuosoDataTableRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event VirtuosoDataTableRowChangeEventHandler VirtuosoDataTableRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddVirtuosoDataTableRow(VirtuosoDataTableRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public VirtuosoDataTableRow AddVirtuosoDataTableRow() {
                VirtuosoDataTableRow rowVirtuosoDataTableRow = ((VirtuosoDataTableRow)(this.NewRow()));
                object[] columnValuesArray = new object[0];
                rowVirtuosoDataTableRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowVirtuosoDataTableRow);
                return rowVirtuosoDataTableRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                VirtuosoDataTableDataTable cln = ((VirtuosoDataTableDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new VirtuosoDataTableDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public VirtuosoDataTableRow NewVirtuosoDataTableRow() {
                return ((VirtuosoDataTableRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new VirtuosoDataTableRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(VirtuosoDataTableRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.VirtuosoDataTableRowChanged != null)) {
                    this.VirtuosoDataTableRowChanged(this, new VirtuosoDataTableRowChangeEvent(((VirtuosoDataTableRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.VirtuosoDataTableRowChanging != null)) {
                    this.VirtuosoDataTableRowChanging(this, new VirtuosoDataTableRowChangeEvent(((VirtuosoDataTableRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.VirtuosoDataTableRowDeleted != null)) {
                    this.VirtuosoDataTableRowDeleted(this, new VirtuosoDataTableRowChangeEvent(((VirtuosoDataTableRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.VirtuosoDataTableRowDeleting != null)) {
                    this.VirtuosoDataTableRowDeleting(this, new VirtuosoDataTableRowChangeEvent(((VirtuosoDataTableRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemoveVirtuosoDataTableRow(VirtuosoDataTableRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                VirtuosoDataSet ds = new VirtuosoDataSet();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "VirtuosoDataTableDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class VirtuosoDataTableRow : global::System.Data.DataRow {
            
            private VirtuosoDataTableDataTable tableVirtuosoDataTable;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal VirtuosoDataTableRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableVirtuosoDataTable = ((VirtuosoDataTableDataTable)(this.Table));
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class VirtuosoDataTableRowChangeEvent : global::System.EventArgs {
            
            private VirtuosoDataTableRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public VirtuosoDataTableRowChangeEvent(VirtuosoDataTableRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public VirtuosoDataTableRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUsers", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string searchString;
        
        public GetUsersRequest() {
        }
        
        public GetUsersRequest(string searchString) {
            this.searchString = searchString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUsersResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public VirtuosoDataSet.VirtuosoDataTableDataTable GetUsersResult;
        
        public GetUsersResponse() {
        }
        
        public GetUsersResponse(VirtuosoDataSet.VirtuosoDataTableDataTable GetUsersResult) {
            this.GetUsersResult = GetUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CollectEvents", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CollectEventsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int SessionNr;
        
        public CollectEventsRequest() {
        }
        
        public CollectEventsRequest(string UserName, string Password, int SessionNr) {
            this.UserName = UserName;
            this.Password = Password;
            this.SessionNr = SessionNr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CollectEventsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CollectEventsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public VirtuosoDataSet.VirtuosoDataTableDataTable CollectEventsResult;
        
        public CollectEventsResponse() {
        }
        
        public CollectEventsResponse(VirtuosoDataSet.VirtuosoDataTableDataTable CollectEventsResult) {
            this.CollectEventsResult = CollectEventsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResetUserpassword", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ResetUserpasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string newPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int sessionNr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adminName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adminPass;
        
        public ResetUserpasswordRequest() {
        }
        
        public ResetUserpasswordRequest(string newPass, string userName, int sessionNr, string adminName, string adminPass) {
            this.newPass = newPass;
            this.userName = userName;
            this.sessionNr = sessionNr;
            this.adminName = adminName;
            this.adminPass = adminPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResetUserpasswordResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ResetUserpasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ResetUserpasswordResult;
        
        public ResetUserpasswordResponse() {
        }
        
        public ResetUserpasswordResponse(bool ResetUserpasswordResult) {
            this.ResetUserpasswordResult = ResetUserpasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetUserAccRights", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetUserAccRightsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool right;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int sessionNr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adminName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adminPass;
        
        public SetUserAccRightsRequest() {
        }
        
        public SetUserAccRightsRequest(bool right, string userName, int sessionNr, string adminName, string adminPass) {
            this.right = right;
            this.userName = userName;
            this.sessionNr = sessionNr;
            this.adminName = adminName;
            this.adminPass = adminPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetUserAccRightsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetUserAccRightsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SetUserAccRightsResult;
        
        public SetUserAccRightsResponse() {
        }
        
        public SetUserAccRightsResponse(bool SetUserAccRightsResult) {
            this.SetUserAccRightsResult = SetUserAccRightsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetEventDefRights", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetEventDefRightsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool right;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int sessionNr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adminName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adminPass;
        
        public SetEventDefRightsRequest() {
        }
        
        public SetEventDefRightsRequest(bool right, string userName, int sessionNr, string adminName, string adminPass) {
            this.right = right;
            this.userName = userName;
            this.sessionNr = sessionNr;
            this.adminName = adminName;
            this.adminPass = adminPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetEventDefRightsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetEventDefRightsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SetEventDefRightsResult;
        
        public SetEventDefRightsResponse() {
        }
        
        public SetEventDefRightsResponse(bool SetEventDefRightsResult) {
            this.SetEventDefRightsResult = SetEventDefRightsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegisterVirtuosoDB", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RegisterVirtuosoDBRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string connectionString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] associatedGraphs;
        
        public RegisterVirtuosoDBRequest() {
        }
        
        public RegisterVirtuosoDBRequest(string connectionString, string[] associatedGraphs) {
            this.connectionString = connectionString;
            this.associatedGraphs = associatedGraphs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegisterVirtuosoDBResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RegisterVirtuosoDBResponse {
        
        public RegisterVirtuosoDBResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVirtuosoEventServiceChannel : RdfEventClientConcoleTest.VirtuosoEventServiceRef.IVirtuosoEventService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VirtuosoEventServiceClient : System.ServiceModel.ClientBase<RdfEventClientConcoleTest.VirtuosoEventServiceRef.IVirtuosoEventService>, RdfEventClientConcoleTest.VirtuosoEventServiceRef.IVirtuosoEventService {
        
        public VirtuosoEventServiceClient() {
        }
        
        public VirtuosoEventServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VirtuosoEventServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VirtuosoEventServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VirtuosoEventServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RdfEventClientConcoleTest.VirtuosoEventServiceRef.GetTriplesResponse RdfEventClientConcoleTest.VirtuosoEventServiceRef.IVirtuosoEventService.GetTriples(RdfEventClientConcoleTest.VirtuosoEventServiceRef.GetTriplesRequest request) {
            return base.Channel.GetTriples(request);
        }
        
        public TripleType[] GetTriples() {
            RdfEventClientConcoleTest.VirtuosoEventServiceRef.GetTriplesRequest inValue = new RdfEventClientConcoleTest.VirtuosoEventServiceRef.GetTriplesRequest();
            RdfEventClientConcoleTest.VirtuosoEventServiceRef.GetTriplesResponse retVal = ((RdfEventClientConcoleTest.VirtuosoEventServiceRef.IVirtuosoEventService)(this)).GetTriples(inValue);
            return retVal.GetTriplesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RdfEventClientConcoleTest.VirtuosoEventServiceRef.GetTripleResponse RdfEventClientConcoleTest.VirtuosoEventServiceRef.IVirtuosoEventService.GetTriple(RdfEventClientConcoleTest.VirtuosoEventServiceRef.GetTripleRequest request) {
            return base.Channel.GetTriple(request);
        }
        
        public RdfEventClientConcoleTest.VirtuosoEventServiceRef.TripleType GetTriple(int index) {
            RdfEventClientConcoleTest.VirtuosoEventServiceRef.GetTripleRequest inValue = new RdfEventClientConcoleTest.VirtuosoEventServiceRef.GetTripleRequest();
            inValue.index = index;
            RdfEventClientConcoleTest.VirtuosoEventServiceRef.GetTripleResponse retVal = ((RdfEventClientConcoleTest.VirtuosoEventServiceRef.IVirtuosoEventService)(this)).GetTriple(inValue);
            return retVal.GetTripleResult;
        }
        
        public void InsertTriple(string graph, string subj, string pred, string obj) {
            base.Channel.InsertTriple(graph, subj, pred, obj);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RdfEventClientConcoleTest.VirtuosoEventServiceRef.LogInResponse RdfEventClientConcoleTest.VirtuosoEventServiceRef.IVirtuosoEventService.LogIn(RdfEventClientConcoleTest.VirtuosoEventServiceRef.LogInRequest request) {
            return base.Channel.LogIn(request);
        }
        
        public string LogIn(string userName, string password) {
            RdfEventClientConcoleTest.VirtuosoEventServiceRef.LogInRequest inValue = new RdfEventClientConcoleTest.VirtuosoEventServiceRef.LogInRequest();
            inValue.userName = userName;
            inValue.password = password;
            RdfEventClientConcoleTest.VirtuosoEventServiceRef.LogInResponse retVal = ((RdfEventClientConcoleTest.VirtuosoEventServiceRef.IVirtuosoEventService)(this)).LogIn(inValue);
            return retVal.LogInResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RdfEventClientConcoleTest.VirtuosoEventServiceRef.CreateNewAccountResponse RdfEventClientConcoleTest.VirtuosoEventServiceRef.IVirtuosoEventService.CreateNewAccount(RdfEventClientConcoleTest.VirtuosoEventServiceRef.CreateNewAccountRequest request) {
            return base.Channel.CreateNewAccount(request);
        }
        
        public bool CreateNewAccount(string userName, string password) {
            RdfEventClientConcoleTest.VirtuosoEventServiceRef.CreateNewAccountRequest inValue = new RdfEventClientConcoleTest.VirtuosoEventServiceRef.CreateNewAccountRequest();
            inValue.userName = userName;
            inValue.password = password;
            RdfEventClientConcoleTest.VirtuosoEventServiceRef.CreateNewAccountResponse retVal = ((RdfEventClientConcoleTest.VirtuosoEventServiceRef.IVirtuosoEventService)(this)).CreateNewAccount(inValue);
            return retVal.CreateNewAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RdfEventClientConcoleTest.VirtuosoEventServiceRef.GetUsersResponse RdfEventClientConcoleTest.VirtuosoEventServiceRef.IVirtuosoEventService.GetUsers(RdfEventClientConcoleTest.VirtuosoEventServiceRef.GetUsersRequest request) {
            return base.Channel.GetUsers(request);
        }
        
        public VirtuosoDataSet.VirtuosoDataTableDataTable GetUsers(string searchString) {
            RdfEventClientConcoleTest.VirtuosoEventServiceRef.GetUsersRequest inValue = new RdfEventClientConcoleTest.VirtuosoEventServiceRef.GetUsersRequest();
            inValue.searchString = searchString;
            RdfEventClientConcoleTest.VirtuosoEventServiceRef.GetUsersResponse retVal = ((RdfEventClientConcoleTest.VirtuosoEventServiceRef.IVirtuosoEventService)(this)).GetUsers(inValue);
            return retVal.GetUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RdfEventClientConcoleTest.VirtuosoEventServiceRef.CollectEventsResponse RdfEventClientConcoleTest.VirtuosoEventServiceRef.IVirtuosoEventService.CollectEvents(RdfEventClientConcoleTest.VirtuosoEventServiceRef.CollectEventsRequest request) {
            return base.Channel.CollectEvents(request);
        }
        
        public VirtuosoDataSet.VirtuosoDataTableDataTable CollectEvents(string UserName, string Password, int SessionNr) {
            RdfEventClientConcoleTest.VirtuosoEventServiceRef.CollectEventsRequest inValue = new RdfEventClientConcoleTest.VirtuosoEventServiceRef.CollectEventsRequest();
            inValue.UserName = UserName;
            inValue.Password = Password;
            inValue.SessionNr = SessionNr;
            RdfEventClientConcoleTest.VirtuosoEventServiceRef.CollectEventsResponse retVal = ((RdfEventClientConcoleTest.VirtuosoEventServiceRef.IVirtuosoEventService)(this)).CollectEvents(inValue);
            return retVal.CollectEventsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RdfEventClientConcoleTest.VirtuosoEventServiceRef.ResetUserpasswordResponse RdfEventClientConcoleTest.VirtuosoEventServiceRef.IVirtuosoEventService.ResetUserpassword(RdfEventClientConcoleTest.VirtuosoEventServiceRef.ResetUserpasswordRequest request) {
            return base.Channel.ResetUserpassword(request);
        }
        
        public bool ResetUserpassword(string newPass, string userName, int sessionNr, string adminName, string adminPass) {
            RdfEventClientConcoleTest.VirtuosoEventServiceRef.ResetUserpasswordRequest inValue = new RdfEventClientConcoleTest.VirtuosoEventServiceRef.ResetUserpasswordRequest();
            inValue.newPass = newPass;
            inValue.userName = userName;
            inValue.sessionNr = sessionNr;
            inValue.adminName = adminName;
            inValue.adminPass = adminPass;
            RdfEventClientConcoleTest.VirtuosoEventServiceRef.ResetUserpasswordResponse retVal = ((RdfEventClientConcoleTest.VirtuosoEventServiceRef.IVirtuosoEventService)(this)).ResetUserpassword(inValue);
            return retVal.ResetUserpasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RdfEventClientConcoleTest.VirtuosoEventServiceRef.SetUserAccRightsResponse RdfEventClientConcoleTest.VirtuosoEventServiceRef.IVirtuosoEventService.SetUserAccRights(RdfEventClientConcoleTest.VirtuosoEventServiceRef.SetUserAccRightsRequest request) {
            return base.Channel.SetUserAccRights(request);
        }
        
        public bool SetUserAccRights(bool right, string userName, int sessionNr, string adminName, string adminPass) {
            RdfEventClientConcoleTest.VirtuosoEventServiceRef.SetUserAccRightsRequest inValue = new RdfEventClientConcoleTest.VirtuosoEventServiceRef.SetUserAccRightsRequest();
            inValue.right = right;
            inValue.userName = userName;
            inValue.sessionNr = sessionNr;
            inValue.adminName = adminName;
            inValue.adminPass = adminPass;
            RdfEventClientConcoleTest.VirtuosoEventServiceRef.SetUserAccRightsResponse retVal = ((RdfEventClientConcoleTest.VirtuosoEventServiceRef.IVirtuosoEventService)(this)).SetUserAccRights(inValue);
            return retVal.SetUserAccRightsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RdfEventClientConcoleTest.VirtuosoEventServiceRef.SetEventDefRightsResponse RdfEventClientConcoleTest.VirtuosoEventServiceRef.IVirtuosoEventService.SetEventDefRights(RdfEventClientConcoleTest.VirtuosoEventServiceRef.SetEventDefRightsRequest request) {
            return base.Channel.SetEventDefRights(request);
        }
        
        public bool SetEventDefRights(bool right, string userName, int sessionNr, string adminName, string adminPass) {
            RdfEventClientConcoleTest.VirtuosoEventServiceRef.SetEventDefRightsRequest inValue = new RdfEventClientConcoleTest.VirtuosoEventServiceRef.SetEventDefRightsRequest();
            inValue.right = right;
            inValue.userName = userName;
            inValue.sessionNr = sessionNr;
            inValue.adminName = adminName;
            inValue.adminPass = adminPass;
            RdfEventClientConcoleTest.VirtuosoEventServiceRef.SetEventDefRightsResponse retVal = ((RdfEventClientConcoleTest.VirtuosoEventServiceRef.IVirtuosoEventService)(this)).SetEventDefRights(inValue);
            return retVal.SetEventDefRightsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RdfEventClientConcoleTest.VirtuosoEventServiceRef.RegisterVirtuosoDBResponse RdfEventClientConcoleTest.VirtuosoEventServiceRef.IVirtuosoEventService.RegisterVirtuosoDB(RdfEventClientConcoleTest.VirtuosoEventServiceRef.RegisterVirtuosoDBRequest request) {
            return base.Channel.RegisterVirtuosoDB(request);
        }
        
        public void RegisterVirtuosoDB(string connectionString, string[] associatedGraphs) {
            RdfEventClientConcoleTest.VirtuosoEventServiceRef.RegisterVirtuosoDBRequest inValue = new RdfEventClientConcoleTest.VirtuosoEventServiceRef.RegisterVirtuosoDBRequest();
            inValue.connectionString = connectionString;
            inValue.associatedGraphs = associatedGraphs;
            RdfEventClientConcoleTest.VirtuosoEventServiceRef.RegisterVirtuosoDBResponse retVal = ((RdfEventClientConcoleTest.VirtuosoEventServiceRef.IVirtuosoEventService)(this)).RegisterVirtuosoDB(inValue);
        }
        
        public bool CreateTrigger() {
            return base.Channel.CreateTrigger();
        }
    }
}
