//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RdfEventClients_AdminTool.EventClientProxyRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EventClientProxyRef.IEventClientNetTcp")]
    public interface IEventClientNetTcp {
        
        // CODEGEN: Parameter 'LogInResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventClientNetTcp/LogIn", ReplyAction="http://tempuri.org/IEventClientNetTcp/LogInResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        RdfEventClients_AdminTool.EventClientProxyRef.LogInResponse LogIn(RdfEventClients_AdminTool.EventClientProxyRef.LogInRequest request);
        
        // CODEGEN: Parameter 'Username' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventClientNetTcp/CreateNewAccount", ReplyAction="http://tempuri.org/IEventClientNetTcp/CreateNewAccountResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        RdfEventClients_AdminTool.EventClientProxyRef.CreateNewAccountResponse CreateNewAccount(RdfEventClients_AdminTool.EventClientProxyRef.CreateNewAccountRequest request);
        
        // CODEGEN: Parameter 'userName' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventClientNetTcp/ResetPassword", ReplyAction="http://tempuri.org/IEventClientNetTcp/ResetPasswordResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        RdfEventClients_AdminTool.EventClientProxyRef.ResetPasswordResponse ResetPassword(RdfEventClients_AdminTool.EventClientProxyRef.ResetPasswordRequest request);
        
        // CODEGEN: Parameter 'userName' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventClientNetTcp/SetUserAccountRights", ReplyAction="http://tempuri.org/IEventClientNetTcp/SetUserAccountRightsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        RdfEventClients_AdminTool.EventClientProxyRef.SetUserAccountRightsResponse SetUserAccountRights(RdfEventClients_AdminTool.EventClientProxyRef.SetUserAccountRightsRequest request);
        
        // CODEGEN: Parameter 'userName' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventClientNetTcp/SetEventDefinitionRights", ReplyAction="http://tempuri.org/IEventClientNetTcp/SetEventDefinitionRightsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        RdfEventClients_AdminTool.EventClientProxyRef.SetEventDefinitionRightsResponse SetEventDefinitionRights(RdfEventClients_AdminTool.EventClientProxyRef.SetEventDefinitionRightsRequest request);
        
        // CODEGEN: Parameter 'GetUsersResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventClientNetTcp/GetUsers", ReplyAction="http://tempuri.org/IEventClientNetTcp/GetUsersResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        RdfEventClients_AdminTool.EventClientProxyRef.GetUsersResponse GetUsers(RdfEventClients_AdminTool.EventClientProxyRef.GetUsersRequest request);
        
        // CODEGEN: Parameter 'Tablename' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventClientNetTcp/RegisterTrigger", ReplyAction="http://tempuri.org/IEventClientNetTcp/RegisterTriggerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        RdfEventClients_AdminTool.EventClientProxyRef.RegisterTriggerResponse RegisterTrigger(RdfEventClients_AdminTool.EventClientProxyRef.RegisterTriggerRequest request);
        
        // CODEGEN: Parameter 'procedureEndpoint' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventClientNetTcp/SetNewRdfTrigger", ReplyAction="http://tempuri.org/IEventClientNetTcp/SetNewRdfTriggerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        RdfEventClients_AdminTool.EventClientProxyRef.SetNewRdfTriggerResponse SetNewRdfTrigger(RdfEventClients_AdminTool.EventClientProxyRef.SetNewRdfTriggerRequest request);
        
        // CODEGEN: Parameter 'GetSchemaTablesResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventClientNetTcp/GetSchemaTables", ReplyAction="http://tempuri.org/IEventClientNetTcp/GetSchemaTablesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        RdfEventClients_AdminTool.EventClientProxyRef.GetSchemaTablesResponse GetSchemaTables(RdfEventClients_AdminTool.EventClientProxyRef.GetSchemaTablesRequest request);
        
        // CODEGEN: Parameter 'GetDatabasesResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventClientNetTcp/GetDatabases", ReplyAction="http://tempuri.org/IEventClientNetTcp/GetDatabasesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        RdfEventClients_AdminTool.EventClientProxyRef.GetDatabasesResponse GetDatabases(RdfEventClients_AdminTool.EventClientProxyRef.GetDatabasesRequest request);
        
        // CODEGEN: Parameter 'GetTriggersOfTableResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventClientNetTcp/GetTriggersOfTable", ReplyAction="http://tempuri.org/IEventClientNetTcp/GetTriggersOfTableResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        RdfEventClients_AdminTool.EventClientProxyRef.GetTriggersOfTableResponse GetTriggersOfTable(RdfEventClients_AdminTool.EventClientProxyRef.GetTriggersOfTableRequest request);
        
        // CODEGEN: Parameter 'GetEventsResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventClientNetTcp/GetEvents", ReplyAction="http://tempuri.org/IEventClientNetTcp/GetEventsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        RdfEventClients_AdminTool.EventClientProxyRef.GetEventsResponse GetEvents(RdfEventClients_AdminTool.EventClientProxyRef.GetEventsRequest request);
        
        // CODEGEN: Parameter 'GetSupportedDBsResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventClientNetTcp/GetSupportedDBs", ReplyAction="http://tempuri.org/IEventClientNetTcp/GetSupportedDBsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        RdfEventClients_AdminTool.EventClientProxyRef.GetSupportedDBsResponse GetSupportedDBs(RdfEventClients_AdminTool.EventClientProxyRef.GetSupportedDBsRequest request);
        
        // CODEGEN: Parameter 'GetRemoteProcedureEndpointResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventClientNetTcp/GetRemoteProcedureEndpoint", ReplyAction="http://tempuri.org/IEventClientNetTcp/GetRemoteProcedureEndpointResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        RdfEventClients_AdminTool.EventClientProxyRef.GetRemoteProcedureEndpointResponse GetRemoteProcedureEndpoint(RdfEventClients_AdminTool.EventClientProxyRef.GetRemoteProcedureEndpointRequest request);
        
        // CODEGEN: Parameter 'RegisterNewRemoteDBResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventClientNetTcp/RegisterNewRemoteDB", ReplyAction="http://tempuri.org/IEventClientNetTcp/RegisterNewRemoteDBResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        RdfEventClients_AdminTool.EventClientProxyRef.RegisterNewRemoteDBResponse RegisterNewRemoteDB(RdfEventClients_AdminTool.EventClientProxyRef.RegisterNewRemoteDBRequest request);
        
        // CODEGEN: Parameter 'ExecuteTestSqlQueryResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEventClientNetTcp/ExecuteTestSqlQuery", ReplyAction="http://tempuri.org/IEventClientNetTcp/ExecuteTestSqlQueryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        RdfEventClients_AdminTool.EventClientProxyRef.ExecuteTestSqlQueryResponse ExecuteTestSqlQuery(RdfEventClients_AdminTool.EventClientProxyRef.ExecuteTestSqlQueryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogIn", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LogInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Password;
        
        public LogInRequest() {
        }
        
        public LogInRequest(string Username, string Password) {
            this.Username = Username;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogInResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LogInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LogInResult;
        
        public LogInResponse() {
        }
        
        public LogInResponse(string LogInResult) {
            this.LogInResult = LogInResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateNewAccount", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateNewAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Password;
        
        public CreateNewAccountRequest() {
        }
        
        public CreateNewAccountRequest(string Username, string Password) {
            this.Username = Username;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateNewAccountResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateNewAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool CreateNewAccountResult;
        
        public CreateNewAccountResponse() {
        }
        
        public CreateNewAccountResponse(bool CreateNewAccountResult) {
            this.CreateNewAccountResult = CreateNewAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResetPassword", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ResetPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string newPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adminPass;
        
        public ResetPasswordRequest() {
        }
        
        public ResetPasswordRequest(string userName, string newPass, string adminPass) {
            this.userName = userName;
            this.newPass = newPass;
            this.adminPass = adminPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResetPasswordResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ResetPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ResetPasswordResult;
        
        public ResetPasswordResponse() {
        }
        
        public ResetPasswordResponse(bool ResetPasswordResult) {
            this.ResetPasswordResult = ResetPasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetUserAccountRights", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetUserAccountRightsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool right;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adminPass;
        
        public SetUserAccountRightsRequest() {
        }
        
        public SetUserAccountRightsRequest(bool right, string userName, string adminPass) {
            this.right = right;
            this.userName = userName;
            this.adminPass = adminPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetUserAccountRightsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetUserAccountRightsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SetUserAccountRightsResult;
        
        public SetUserAccountRightsResponse() {
        }
        
        public SetUserAccountRightsResponse(bool SetUserAccountRightsResult) {
            this.SetUserAccountRightsResult = SetUserAccountRightsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetEventDefinitionRights", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetEventDefinitionRightsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool right;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adminPass;
        
        public SetEventDefinitionRightsRequest() {
        }
        
        public SetEventDefinitionRightsRequest(bool right, string userName, string adminPass) {
            this.right = right;
            this.userName = userName;
            this.adminPass = adminPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetEventDefinitionRightsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetEventDefinitionRightsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SetEventDefinitionRightsResult;
        
        public SetEventDefinitionRightsResponse() {
        }
        
        public SetEventDefinitionRightsResponse(bool SetEventDefinitionRightsResult) {
            this.SetEventDefinitionRightsResult = SetEventDefinitionRightsResult;
        }
    }
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    // This type definition was generated by System.Data.Design.TypedDataSetSchemaImporterExtensionFx35 schema importer extension.
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("VirtuosoDataSet")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class VirtuosoDataSet : global::System.Data.DataSet {
        
        private VirtuosoDataTableDataTable tableVirtuosoDataTable;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public VirtuosoDataSet() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected VirtuosoDataSet(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["VirtuosoDataTable"] != null)) {
                    base.Tables.Add(new VirtuosoDataTableDataTable(ds.Tables["VirtuosoDataTable"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public VirtuosoDataTableDataTable VirtuosoDataTable {
            get {
                return this.tableVirtuosoDataTable;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            VirtuosoDataSet cln = ((VirtuosoDataSet)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["VirtuosoDataTable"] != null)) {
                    base.Tables.Add(new VirtuosoDataTableDataTable(ds.Tables["VirtuosoDataTable"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableVirtuosoDataTable = ((VirtuosoDataTableDataTable)(base.Tables["VirtuosoDataTable"]));
            if ((initTable == true)) {
                if ((this.tableVirtuosoDataTable != null)) {
                    this.tableVirtuosoDataTable.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "VirtuosoDataSet";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/VirtuosoDataSet.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableVirtuosoDataTable = new VirtuosoDataTableDataTable();
            base.Tables.Add(this.tableVirtuosoDataTable);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializeVirtuosoDataTable() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            VirtuosoDataSet ds = new VirtuosoDataSet();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void VirtuosoDataTableRowChangeEventHandler(object sender, VirtuosoDataTableRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class VirtuosoDataTableDataTable : global::System.Data.TypedTableBase<VirtuosoDataTableRow> {
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public VirtuosoDataTableDataTable() {
                this.TableName = "VirtuosoDataTable";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal VirtuosoDataTableDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected VirtuosoDataTableDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public VirtuosoDataTableRow this[int index] {
                get {
                    return ((VirtuosoDataTableRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event VirtuosoDataTableRowChangeEventHandler VirtuosoDataTableRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event VirtuosoDataTableRowChangeEventHandler VirtuosoDataTableRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event VirtuosoDataTableRowChangeEventHandler VirtuosoDataTableRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event VirtuosoDataTableRowChangeEventHandler VirtuosoDataTableRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddVirtuosoDataTableRow(VirtuosoDataTableRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public VirtuosoDataTableRow AddVirtuosoDataTableRow() {
                VirtuosoDataTableRow rowVirtuosoDataTableRow = ((VirtuosoDataTableRow)(this.NewRow()));
                object[] columnValuesArray = new object[0];
                rowVirtuosoDataTableRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowVirtuosoDataTableRow);
                return rowVirtuosoDataTableRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                VirtuosoDataTableDataTable cln = ((VirtuosoDataTableDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new VirtuosoDataTableDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public VirtuosoDataTableRow NewVirtuosoDataTableRow() {
                return ((VirtuosoDataTableRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new VirtuosoDataTableRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(VirtuosoDataTableRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.VirtuosoDataTableRowChanged != null)) {
                    this.VirtuosoDataTableRowChanged(this, new VirtuosoDataTableRowChangeEvent(((VirtuosoDataTableRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.VirtuosoDataTableRowChanging != null)) {
                    this.VirtuosoDataTableRowChanging(this, new VirtuosoDataTableRowChangeEvent(((VirtuosoDataTableRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.VirtuosoDataTableRowDeleted != null)) {
                    this.VirtuosoDataTableRowDeleted(this, new VirtuosoDataTableRowChangeEvent(((VirtuosoDataTableRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.VirtuosoDataTableRowDeleting != null)) {
                    this.VirtuosoDataTableRowDeleting(this, new VirtuosoDataTableRowChangeEvent(((VirtuosoDataTableRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemoveVirtuosoDataTableRow(VirtuosoDataTableRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                VirtuosoDataSet ds = new VirtuosoDataSet();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "VirtuosoDataTableDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class VirtuosoDataTableRow : global::System.Data.DataRow {
            
            private VirtuosoDataTableDataTable tableVirtuosoDataTable;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal VirtuosoDataTableRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableVirtuosoDataTable = ((VirtuosoDataTableDataTable)(this.Table));
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class VirtuosoDataTableRowChangeEvent : global::System.EventArgs {
            
            private VirtuosoDataTableRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public VirtuosoDataTableRowChangeEvent(VirtuosoDataTableRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public VirtuosoDataTableRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUsers", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string namePart;
        
        public GetUsersRequest() {
        }
        
        public GetUsersRequest(string namePart) {
            this.namePart = namePart;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUsersResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public VirtuosoDataSet.VirtuosoDataTableDataTable GetUsersResult;
        
        public GetUsersResponse() {
        }
        
        public GetUsersResponse(VirtuosoDataSet.VirtuosoDataTableDataTable GetUsersResult) {
            this.GetUsersResult = GetUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegisterTrigger", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RegisterTriggerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int DBInstance;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Tablename;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Triggername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string procedureEndpoint;
        
        public RegisterTriggerRequest() {
        }
        
        public RegisterTriggerRequest(int DBInstance, string Tablename, string Triggername, string procedureEndpoint) {
            this.DBInstance = DBInstance;
            this.Tablename = Tablename;
            this.Triggername = Triggername;
            this.procedureEndpoint = procedureEndpoint;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegisterTriggerResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RegisterTriggerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool RegisterTriggerResult;
        
        public RegisterTriggerResponse() {
        }
        
        public RegisterTriggerResponse(bool RegisterTriggerResult) {
            this.RegisterTriggerResult = RegisterTriggerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetNewRdfTrigger", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetNewRdfTriggerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string procedureEndpoint;
        
        public SetNewRdfTriggerRequest() {
        }
        
        public SetNewRdfTriggerRequest(string procedureEndpoint) {
            this.procedureEndpoint = procedureEndpoint;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetNewRdfTriggerResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetNewRdfTriggerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SetNewRdfTriggerResult;
        
        public SetNewRdfTriggerResponse() {
        }
        
        public SetNewRdfTriggerResponse(bool SetNewRdfTriggerResult) {
            this.SetNewRdfTriggerResult = SetNewRdfTriggerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSchemaTables", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSchemaTablesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string schema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string procedureEndpoint;
        
        public GetSchemaTablesRequest() {
        }
        
        public GetSchemaTablesRequest(string schema, string procedureEndpoint) {
            this.schema = schema;
            this.procedureEndpoint = procedureEndpoint;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSchemaTablesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSchemaTablesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] GetSchemaTablesResult;
        
        public GetSchemaTablesResponse() {
        }
        
        public GetSchemaTablesResponse(string[] GetSchemaTablesResult) {
            this.GetSchemaTablesResult = GetSchemaTablesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDatabases", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDatabasesRequest {
        
        public GetDatabasesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDatabasesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDatabasesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public VirtuosoDataSet.VirtuosoDataTableDataTable GetDatabasesResult;
        
        public GetDatabasesResponse() {
        }
        
        public GetDatabasesResponse(VirtuosoDataSet.VirtuosoDataTableDataTable GetDatabasesResult) {
            this.GetDatabasesResult = GetDatabasesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTriggersOfTable", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTriggersOfTableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tableName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string procedureEndpoint;
        
        public GetTriggersOfTableRequest() {
        }
        
        public GetTriggersOfTableRequest(string tableName, string procedureEndpoint) {
            this.tableName = tableName;
            this.procedureEndpoint = procedureEndpoint;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTriggersOfTableResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTriggersOfTableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] GetTriggersOfTableResult;
        
        public GetTriggersOfTableResponse() {
        }
        
        public GetTriggersOfTableResponse(string[] GetTriggersOfTableResult) {
            this.GetTriggersOfTableResult = GetTriggersOfTableResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEvents", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetEventsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int minutes;
        
        public GetEventsRequest() {
        }
        
        public GetEventsRequest(int minutes) {
            this.minutes = minutes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEventsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetEventsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public VirtuosoDataSet.VirtuosoDataTableDataTable GetEventsResult;
        
        public GetEventsResponse() {
        }
        
        public GetEventsResponse(VirtuosoDataSet.VirtuosoDataTableDataTable GetEventsResult) {
            this.GetEventsResult = GetEventsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSupportedDBs", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSupportedDBsRequest {
        
        public GetSupportedDBsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSupportedDBsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSupportedDBsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetSupportedDBsResult;
        
        public GetSupportedDBsResponse() {
        }
        
        public GetSupportedDBsResponse(string GetSupportedDBsResult) {
            this.GetSupportedDBsResult = GetSupportedDBsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRemoteProcedureEndpoint", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRemoteProcedureEndpointRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int dbInstance;
        
        public GetRemoteProcedureEndpointRequest() {
        }
        
        public GetRemoteProcedureEndpointRequest(int dbInstance) {
            this.dbInstance = dbInstance;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRemoteProcedureEndpointResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRemoteProcedureEndpointResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetRemoteProcedureEndpointResult;
        
        public GetRemoteProcedureEndpointResponse() {
        }
        
        public GetRemoteProcedureEndpointResponse(string GetRemoteProcedureEndpointResult) {
            this.GetRemoteProcedureEndpointResult = GetRemoteProcedureEndpointResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegisterNewRemoteDB", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RegisterNewRemoteDBRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dbType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string remoteEndpoint;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string description;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sparqlEndpoint;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string graphUris;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string catalogSchema;
        
        public RegisterNewRemoteDBRequest() {
        }
        
        public RegisterNewRemoteDBRequest(string dbType, string remoteEndpoint, string description, string sparqlEndpoint, string graphUris, string catalogSchema) {
            this.dbType = dbType;
            this.remoteEndpoint = remoteEndpoint;
            this.description = description;
            this.sparqlEndpoint = sparqlEndpoint;
            this.graphUris = graphUris;
            this.catalogSchema = catalogSchema;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegisterNewRemoteDBResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RegisterNewRemoteDBResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RegisterNewRemoteDBResult;
        
        public RegisterNewRemoteDBResponse() {
        }
        
        public RegisterNewRemoteDBResponse(string RegisterNewRemoteDBResult) {
            this.RegisterNewRemoteDBResult = RegisterNewRemoteDBResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteTestSqlQuery", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecuteTestSqlQueryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string querryString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string procedureEndpoint;
        
        public ExecuteTestSqlQueryRequest() {
        }
        
        public ExecuteTestSqlQueryRequest(string querryString, string procedureEndpoint) {
            this.querryString = querryString;
            this.procedureEndpoint = procedureEndpoint;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteTestSqlQueryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecuteTestSqlQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfstring", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", NestingLevel=1)]
        public string[][] ExecuteTestSqlQueryResult;
        
        public ExecuteTestSqlQueryResponse() {
        }
        
        public ExecuteTestSqlQueryResponse(string[][] ExecuteTestSqlQueryResult) {
            this.ExecuteTestSqlQueryResult = ExecuteTestSqlQueryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEventClientNetTcpChannel : RdfEventClients_AdminTool.EventClientProxyRef.IEventClientNetTcp, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EventClientNetTcpClient : System.ServiceModel.ClientBase<RdfEventClients_AdminTool.EventClientProxyRef.IEventClientNetTcp>, RdfEventClients_AdminTool.EventClientProxyRef.IEventClientNetTcp {
        
        public EventClientNetTcpClient() {
        }
        
        public EventClientNetTcpClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EventClientNetTcpClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventClientNetTcpClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventClientNetTcpClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RdfEventClients_AdminTool.EventClientProxyRef.LogInResponse RdfEventClients_AdminTool.EventClientProxyRef.IEventClientNetTcp.LogIn(RdfEventClients_AdminTool.EventClientProxyRef.LogInRequest request) {
            return base.Channel.LogIn(request);
        }
        
        public string LogIn(string Username, string Password) {
            RdfEventClients_AdminTool.EventClientProxyRef.LogInRequest inValue = new RdfEventClients_AdminTool.EventClientProxyRef.LogInRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            RdfEventClients_AdminTool.EventClientProxyRef.LogInResponse retVal = ((RdfEventClients_AdminTool.EventClientProxyRef.IEventClientNetTcp)(this)).LogIn(inValue);
            return retVal.LogInResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RdfEventClients_AdminTool.EventClientProxyRef.CreateNewAccountResponse RdfEventClients_AdminTool.EventClientProxyRef.IEventClientNetTcp.CreateNewAccount(RdfEventClients_AdminTool.EventClientProxyRef.CreateNewAccountRequest request) {
            return base.Channel.CreateNewAccount(request);
        }
        
        public bool CreateNewAccount(string Username, string Password) {
            RdfEventClients_AdminTool.EventClientProxyRef.CreateNewAccountRequest inValue = new RdfEventClients_AdminTool.EventClientProxyRef.CreateNewAccountRequest();
            inValue.Username = Username;
            inValue.Password = Password;
            RdfEventClients_AdminTool.EventClientProxyRef.CreateNewAccountResponse retVal = ((RdfEventClients_AdminTool.EventClientProxyRef.IEventClientNetTcp)(this)).CreateNewAccount(inValue);
            return retVal.CreateNewAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RdfEventClients_AdminTool.EventClientProxyRef.ResetPasswordResponse RdfEventClients_AdminTool.EventClientProxyRef.IEventClientNetTcp.ResetPassword(RdfEventClients_AdminTool.EventClientProxyRef.ResetPasswordRequest request) {
            return base.Channel.ResetPassword(request);
        }
        
        public bool ResetPassword(string userName, string newPass, string adminPass) {
            RdfEventClients_AdminTool.EventClientProxyRef.ResetPasswordRequest inValue = new RdfEventClients_AdminTool.EventClientProxyRef.ResetPasswordRequest();
            inValue.userName = userName;
            inValue.newPass = newPass;
            inValue.adminPass = adminPass;
            RdfEventClients_AdminTool.EventClientProxyRef.ResetPasswordResponse retVal = ((RdfEventClients_AdminTool.EventClientProxyRef.IEventClientNetTcp)(this)).ResetPassword(inValue);
            return retVal.ResetPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RdfEventClients_AdminTool.EventClientProxyRef.SetUserAccountRightsResponse RdfEventClients_AdminTool.EventClientProxyRef.IEventClientNetTcp.SetUserAccountRights(RdfEventClients_AdminTool.EventClientProxyRef.SetUserAccountRightsRequest request) {
            return base.Channel.SetUserAccountRights(request);
        }
        
        public bool SetUserAccountRights(bool right, string userName, string adminPass) {
            RdfEventClients_AdminTool.EventClientProxyRef.SetUserAccountRightsRequest inValue = new RdfEventClients_AdminTool.EventClientProxyRef.SetUserAccountRightsRequest();
            inValue.right = right;
            inValue.userName = userName;
            inValue.adminPass = adminPass;
            RdfEventClients_AdminTool.EventClientProxyRef.SetUserAccountRightsResponse retVal = ((RdfEventClients_AdminTool.EventClientProxyRef.IEventClientNetTcp)(this)).SetUserAccountRights(inValue);
            return retVal.SetUserAccountRightsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RdfEventClients_AdminTool.EventClientProxyRef.SetEventDefinitionRightsResponse RdfEventClients_AdminTool.EventClientProxyRef.IEventClientNetTcp.SetEventDefinitionRights(RdfEventClients_AdminTool.EventClientProxyRef.SetEventDefinitionRightsRequest request) {
            return base.Channel.SetEventDefinitionRights(request);
        }
        
        public bool SetEventDefinitionRights(bool right, string userName, string adminPass) {
            RdfEventClients_AdminTool.EventClientProxyRef.SetEventDefinitionRightsRequest inValue = new RdfEventClients_AdminTool.EventClientProxyRef.SetEventDefinitionRightsRequest();
            inValue.right = right;
            inValue.userName = userName;
            inValue.adminPass = adminPass;
            RdfEventClients_AdminTool.EventClientProxyRef.SetEventDefinitionRightsResponse retVal = ((RdfEventClients_AdminTool.EventClientProxyRef.IEventClientNetTcp)(this)).SetEventDefinitionRights(inValue);
            return retVal.SetEventDefinitionRightsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RdfEventClients_AdminTool.EventClientProxyRef.GetUsersResponse RdfEventClients_AdminTool.EventClientProxyRef.IEventClientNetTcp.GetUsers(RdfEventClients_AdminTool.EventClientProxyRef.GetUsersRequest request) {
            return base.Channel.GetUsers(request);
        }
        
        public VirtuosoDataSet.VirtuosoDataTableDataTable GetUsers(string namePart) {
            RdfEventClients_AdminTool.EventClientProxyRef.GetUsersRequest inValue = new RdfEventClients_AdminTool.EventClientProxyRef.GetUsersRequest();
            inValue.namePart = namePart;
            RdfEventClients_AdminTool.EventClientProxyRef.GetUsersResponse retVal = ((RdfEventClients_AdminTool.EventClientProxyRef.IEventClientNetTcp)(this)).GetUsers(inValue);
            return retVal.GetUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RdfEventClients_AdminTool.EventClientProxyRef.RegisterTriggerResponse RdfEventClients_AdminTool.EventClientProxyRef.IEventClientNetTcp.RegisterTrigger(RdfEventClients_AdminTool.EventClientProxyRef.RegisterTriggerRequest request) {
            return base.Channel.RegisterTrigger(request);
        }
        
        public bool RegisterTrigger(int DBInstance, string Tablename, string Triggername, string procedureEndpoint) {
            RdfEventClients_AdminTool.EventClientProxyRef.RegisterTriggerRequest inValue = new RdfEventClients_AdminTool.EventClientProxyRef.RegisterTriggerRequest();
            inValue.DBInstance = DBInstance;
            inValue.Tablename = Tablename;
            inValue.Triggername = Triggername;
            inValue.procedureEndpoint = procedureEndpoint;
            RdfEventClients_AdminTool.EventClientProxyRef.RegisterTriggerResponse retVal = ((RdfEventClients_AdminTool.EventClientProxyRef.IEventClientNetTcp)(this)).RegisterTrigger(inValue);
            return retVal.RegisterTriggerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RdfEventClients_AdminTool.EventClientProxyRef.SetNewRdfTriggerResponse RdfEventClients_AdminTool.EventClientProxyRef.IEventClientNetTcp.SetNewRdfTrigger(RdfEventClients_AdminTool.EventClientProxyRef.SetNewRdfTriggerRequest request) {
            return base.Channel.SetNewRdfTrigger(request);
        }
        
        public bool SetNewRdfTrigger(string procedureEndpoint) {
            RdfEventClients_AdminTool.EventClientProxyRef.SetNewRdfTriggerRequest inValue = new RdfEventClients_AdminTool.EventClientProxyRef.SetNewRdfTriggerRequest();
            inValue.procedureEndpoint = procedureEndpoint;
            RdfEventClients_AdminTool.EventClientProxyRef.SetNewRdfTriggerResponse retVal = ((RdfEventClients_AdminTool.EventClientProxyRef.IEventClientNetTcp)(this)).SetNewRdfTrigger(inValue);
            return retVal.SetNewRdfTriggerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RdfEventClients_AdminTool.EventClientProxyRef.GetSchemaTablesResponse RdfEventClients_AdminTool.EventClientProxyRef.IEventClientNetTcp.GetSchemaTables(RdfEventClients_AdminTool.EventClientProxyRef.GetSchemaTablesRequest request) {
            return base.Channel.GetSchemaTables(request);
        }
        
        public string[] GetSchemaTables(string schema, string procedureEndpoint) {
            RdfEventClients_AdminTool.EventClientProxyRef.GetSchemaTablesRequest inValue = new RdfEventClients_AdminTool.EventClientProxyRef.GetSchemaTablesRequest();
            inValue.schema = schema;
            inValue.procedureEndpoint = procedureEndpoint;
            RdfEventClients_AdminTool.EventClientProxyRef.GetSchemaTablesResponse retVal = ((RdfEventClients_AdminTool.EventClientProxyRef.IEventClientNetTcp)(this)).GetSchemaTables(inValue);
            return retVal.GetSchemaTablesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RdfEventClients_AdminTool.EventClientProxyRef.GetDatabasesResponse RdfEventClients_AdminTool.EventClientProxyRef.IEventClientNetTcp.GetDatabases(RdfEventClients_AdminTool.EventClientProxyRef.GetDatabasesRequest request) {
            return base.Channel.GetDatabases(request);
        }
        
        public VirtuosoDataSet.VirtuosoDataTableDataTable GetDatabases() {
            RdfEventClients_AdminTool.EventClientProxyRef.GetDatabasesRequest inValue = new RdfEventClients_AdminTool.EventClientProxyRef.GetDatabasesRequest();
            RdfEventClients_AdminTool.EventClientProxyRef.GetDatabasesResponse retVal = ((RdfEventClients_AdminTool.EventClientProxyRef.IEventClientNetTcp)(this)).GetDatabases(inValue);
            return retVal.GetDatabasesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RdfEventClients_AdminTool.EventClientProxyRef.GetTriggersOfTableResponse RdfEventClients_AdminTool.EventClientProxyRef.IEventClientNetTcp.GetTriggersOfTable(RdfEventClients_AdminTool.EventClientProxyRef.GetTriggersOfTableRequest request) {
            return base.Channel.GetTriggersOfTable(request);
        }
        
        public string[] GetTriggersOfTable(string tableName, string procedureEndpoint) {
            RdfEventClients_AdminTool.EventClientProxyRef.GetTriggersOfTableRequest inValue = new RdfEventClients_AdminTool.EventClientProxyRef.GetTriggersOfTableRequest();
            inValue.tableName = tableName;
            inValue.procedureEndpoint = procedureEndpoint;
            RdfEventClients_AdminTool.EventClientProxyRef.GetTriggersOfTableResponse retVal = ((RdfEventClients_AdminTool.EventClientProxyRef.IEventClientNetTcp)(this)).GetTriggersOfTable(inValue);
            return retVal.GetTriggersOfTableResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RdfEventClients_AdminTool.EventClientProxyRef.GetEventsResponse RdfEventClients_AdminTool.EventClientProxyRef.IEventClientNetTcp.GetEvents(RdfEventClients_AdminTool.EventClientProxyRef.GetEventsRequest request) {
            return base.Channel.GetEvents(request);
        }
        
        public VirtuosoDataSet.VirtuosoDataTableDataTable GetEvents(int minutes) {
            RdfEventClients_AdminTool.EventClientProxyRef.GetEventsRequest inValue = new RdfEventClients_AdminTool.EventClientProxyRef.GetEventsRequest();
            inValue.minutes = minutes;
            RdfEventClients_AdminTool.EventClientProxyRef.GetEventsResponse retVal = ((RdfEventClients_AdminTool.EventClientProxyRef.IEventClientNetTcp)(this)).GetEvents(inValue);
            return retVal.GetEventsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RdfEventClients_AdminTool.EventClientProxyRef.GetSupportedDBsResponse RdfEventClients_AdminTool.EventClientProxyRef.IEventClientNetTcp.GetSupportedDBs(RdfEventClients_AdminTool.EventClientProxyRef.GetSupportedDBsRequest request) {
            return base.Channel.GetSupportedDBs(request);
        }
        
        public string GetSupportedDBs() {
            RdfEventClients_AdminTool.EventClientProxyRef.GetSupportedDBsRequest inValue = new RdfEventClients_AdminTool.EventClientProxyRef.GetSupportedDBsRequest();
            RdfEventClients_AdminTool.EventClientProxyRef.GetSupportedDBsResponse retVal = ((RdfEventClients_AdminTool.EventClientProxyRef.IEventClientNetTcp)(this)).GetSupportedDBs(inValue);
            return retVal.GetSupportedDBsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RdfEventClients_AdminTool.EventClientProxyRef.GetRemoteProcedureEndpointResponse RdfEventClients_AdminTool.EventClientProxyRef.IEventClientNetTcp.GetRemoteProcedureEndpoint(RdfEventClients_AdminTool.EventClientProxyRef.GetRemoteProcedureEndpointRequest request) {
            return base.Channel.GetRemoteProcedureEndpoint(request);
        }
        
        public string GetRemoteProcedureEndpoint(int dbInstance) {
            RdfEventClients_AdminTool.EventClientProxyRef.GetRemoteProcedureEndpointRequest inValue = new RdfEventClients_AdminTool.EventClientProxyRef.GetRemoteProcedureEndpointRequest();
            inValue.dbInstance = dbInstance;
            RdfEventClients_AdminTool.EventClientProxyRef.GetRemoteProcedureEndpointResponse retVal = ((RdfEventClients_AdminTool.EventClientProxyRef.IEventClientNetTcp)(this)).GetRemoteProcedureEndpoint(inValue);
            return retVal.GetRemoteProcedureEndpointResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RdfEventClients_AdminTool.EventClientProxyRef.RegisterNewRemoteDBResponse RdfEventClients_AdminTool.EventClientProxyRef.IEventClientNetTcp.RegisterNewRemoteDB(RdfEventClients_AdminTool.EventClientProxyRef.RegisterNewRemoteDBRequest request) {
            return base.Channel.RegisterNewRemoteDB(request);
        }
        
        public string RegisterNewRemoteDB(string dbType, string remoteEndpoint, string description, string sparqlEndpoint, string graphUris, string catalogSchema) {
            RdfEventClients_AdminTool.EventClientProxyRef.RegisterNewRemoteDBRequest inValue = new RdfEventClients_AdminTool.EventClientProxyRef.RegisterNewRemoteDBRequest();
            inValue.dbType = dbType;
            inValue.remoteEndpoint = remoteEndpoint;
            inValue.description = description;
            inValue.sparqlEndpoint = sparqlEndpoint;
            inValue.graphUris = graphUris;
            inValue.catalogSchema = catalogSchema;
            RdfEventClients_AdminTool.EventClientProxyRef.RegisterNewRemoteDBResponse retVal = ((RdfEventClients_AdminTool.EventClientProxyRef.IEventClientNetTcp)(this)).RegisterNewRemoteDB(inValue);
            return retVal.RegisterNewRemoteDBResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RdfEventClients_AdminTool.EventClientProxyRef.ExecuteTestSqlQueryResponse RdfEventClients_AdminTool.EventClientProxyRef.IEventClientNetTcp.ExecuteTestSqlQuery(RdfEventClients_AdminTool.EventClientProxyRef.ExecuteTestSqlQueryRequest request) {
            return base.Channel.ExecuteTestSqlQuery(request);
        }
        
        public string[][] ExecuteTestSqlQuery(string querryString, string procedureEndpoint) {
            RdfEventClients_AdminTool.EventClientProxyRef.ExecuteTestSqlQueryRequest inValue = new RdfEventClients_AdminTool.EventClientProxyRef.ExecuteTestSqlQueryRequest();
            inValue.querryString = querryString;
            inValue.procedureEndpoint = procedureEndpoint;
            RdfEventClients_AdminTool.EventClientProxyRef.ExecuteTestSqlQueryResponse retVal = ((RdfEventClients_AdminTool.EventClientProxyRef.IEventClientNetTcp)(this)).ExecuteTestSqlQuery(inValue);
            return retVal.ExecuteTestSqlQueryResult;
        }
    }
}
